config/routes.rb
Rails.application.routes.draw do
  resources :ingredients

   root 'ingredients#index'

end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
   
   before_save :from_to_geocode
   
   def from_to_geocode
     from_adr = Geocoder.coordinates(from)
     to_adr = Geocoder.coordinates(to)
     self.from_latitude = from_adr.first
     self.from_longitude = from_adr.last
     self.to_latitude = to_adr.first
     self.to_longitude = to_adr.last
   end
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
   
   before_save :from_to_geocode
   
   def from_to_geocode
     from_adr = Geocoder.coordinates(from)
     to_adr = Geocoder.coordinates(to)
     self.from_latitude = from_adr.first
     self.from_longitude = from_adr.last
     self.to_latitude = to_adr.first
     self.to_longitude = to_adr.last
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])
    gon.f_lat =@ingredient.from_latitude 
    gon.f_lng =@ingredient.from_longitude
    gon.t_lat =@ingredient.to_latitude 
    gon.t_lng =@ingredient.to_longitude
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingrediënt toegevoegd.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingrediënt aangepast.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingrediënt verwijderd.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:sender, :reciever, :from, :to, :contents, :from_latitude, :from_longitude, :to_latitude, :to_longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deliveries/new.html.erb
<h1>New Delivery</h1>

<%= render 'form' %>

<%= link_to 'Back', deliveries_path %>

app/views/deliveries/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
	<div class="col-md-5">
	<p>
	  <strong>Sender:</strong>
	  <%= @delivery.sender %>
	</p>

	<p>
	  <strong>Reciever:</strong>
	  <%= @delivery.reciever %>
	</p>

	<p>
	  <strong>From:</strong>
	  <%= @delivery.from %>
	</p>

	<p>
	  <strong>To:</strong>
	  <%= @delivery.to %>
	</p>

	<p>
	  <strong>Contents:</strong>
	  <%= @delivery.contents %>
	</p>

	<%= link_to 'Edit', edit_delivery_path(@delivery) %> |
	<%= link_to 'Back', deliveries_path %>
</div>
<div class="col-md-7">
	<div style='width: 800px;'>
	  <div id="directions" style='width: 700px; height: 400px;'></div>
	</div>
</div>

</div>



<script type="text/javascript">
var directionsDisplay = new google.maps.DirectionsRenderer();
var directionsService = new google.maps.DirectionsService();

function calcRoute() {
  var origin      = new google.maps.LatLng(gon.f_lat, gon.f_lng);
  var destination = new google.maps.LatLng(gon.t_lat, gon.t_lng);
  var request = {
      origin:      origin,
      destination: destination,
      travelMode:  google.maps.TravelMode.DRIVING
  };
  directionsService.route(request, function(response, status) {
    if (status == google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);
    }
  });
}

calcRoute();

var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'directions'}}, function(){
	
  directionsDisplay.setMap(handler.getMap());
});
</script>

app/views/ingredients/_form.html.erb
<%= simple_form_for @ingredient do |f| %>
	<%= f.input :reciever, placeholder: "Naam recept" %>
	<%= f.input :from, placeholder: "Locatie ingrediënt 1"%>
	<%= f.input :to, placeholder: "Locatie ingrediënt 2" %>
	<%= f.input :contents, placeholder: "Overige ingredienten" %>
	<%= f.submit "Toevoegen", class: "button"%>
<% end %>
<br/>

app/views/ingredients/edit.html.erb
<h4>Ingredient aanpassen</h4>

<%= render 'form' %>


<%= link_to 'Terug', ingredients_path, :class => "button" %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>
<table class="u-full-width">
  <thead>
    <tr>
      <th>Ingredient</th>
      <th>Van</th>
      <th>Naar</th>
      <th>Beschrijving</th>
    </tr>
  </thead>
  <tbody>
   <% @ingredients.each do |ingredient| %>
    <tr>
      <td><%= ingredient.reciever %></td>
      <td><%= ingredient.from %></td>
      <td><%= ingredient.to %></td>
      <td><%= ingredient.contents %></td>
      <td><%= link_to 'Bekijken', ingredient %></td>
      <td><%= link_to 'Aanpassen', edit_ingredient_path(ingredient) %></td>
      <td><%= link_to 'Verwijderen', ingredient, method: :delete, data: { confirm: 'Bevestig verwijdering van ingrediënt' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Nieuw ingredient', new_ingredient_path, :class => "button" %>
<br>
<div class="row">
<div class="two columns">
 <div style='width: 800px;'>
    <div id="geolocation" style='width: 800px; height: 400px;'></div>
  </div>
  </div>
  </div>

<script type="text/javascript">
  var handler = Gmaps.build('Google');
  
handler.buildMap({ internal: {id: 'geolocation'} }, function(){
  if(navigator.geolocation)
    navigator.geolocation.getCurrentPosition(displayOnMap);
});

function displayOnMap(position){

  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude

  });
  handler.map.centerOn(marker);
};
</script>

app/views/ingredients/new.html.erb
<h4>Nieuw ingrediënt</h4>

<%= render 'form' %>

<%= link_to 'Terug',  ingredients_path, :class => "button"%>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
	<div class="four columns">
	<p>
	  <strong>Reciever:</strong>
	  <%= @ingredient.reciever %>
	</p>

	<p>
	  <strong>From:</strong>
	  <%= @ingredient.from %>
	</p>

	<p>
	  <strong>To:</strong>
	  <%= @ingredient.to %>
	</p>

	<p>
	  <strong>Contents:</strong>
	  <%= @ingredient.contents %>
	</p>

	<%= link_to 'Aanpassen', edit_ingredient_path(@ingredient) %> |
	<%= link_to 'Terug', ingredients_path %>
</div>
<div class="seven columns">
	<div style='width: 800px;'>
	  <div id="directions" style='width: 700px; height: 400px;'></div>
	</div>
</div>

</div>



<script type="text/javascript">
var directionsDisplay = new google.maps.DirectionsRenderer();
var directionsService = new google.maps.DirectionsService();

function calcRoute() {
  var origin      = new google.maps.LatLng(gon.f_lat, gon.f_lng);
  var destination = new google.maps.LatLng(gon.t_lat, gon.t_lng);
  var request = {
      origin:      origin,
      destination: destination,
      travelMode:  google.maps.TravelMode.WALKING
  };
  directionsService.route(request, function(response, status) {
    if (status == google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);	
    }
  });
}

calcRoute();

var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'directions'}}, function(){
	
  directionsDisplay.setMap(handler.getMap());
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
	<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <title>Recappt</title>
	<%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<div class="row">
		<%= yield %>
	</div>
</div>
</body>
</html>